export const EMBEDDING_DIMENSIONS = 1536;
export const MAX_VARCHAR_LENGTH = 191;
export const MAXIMUM_TEXT_LENGTH_FOR_MARKDOWN_CONVERSION = 10000;
export const MAXIMUM_FILE_SIZE_IN_BYTES = 5 * 1024 * 1024;
export const PREVIEW_TEXT_LENGTH = 300;
export const VECTOR_SEARCH_K = 4;
export const MAXIMUM_NUMBER_OF_FILES_IN_THREAD = 30;
export const SIMILARITY_THRESHOLD = 0.5;
